using System;
using System.Collections.Generic;
using System.Text;

namespace DataAccess
{
    public class SeedLocalGovt
    {
        public static List<LocalGovt> AddSeedLocalGovt()
        {
            List<LocalGovt> localGovts = new List<LocalGovt>();
            localGovts.Add(new LocalGovt { StateId = 1, Name = "Aba North" });
            localGovts.Add(new LocalGovt { StateId = 1, Name = "Aba South" });
            localGovts.Add(new LocalGovt { StateId = 1, Name = "Arochukwu" });
            localGovts.Add(new LocalGovt { StateId = 1, Name = "Bende" });
            localGovts.Add(new LocalGovt { StateId = 1, Name = "Ikwuano" });
            localGovts.Add(new LocalGovt { StateId = 1, Name = "Isiala Ngwa North" });
            localGovts.Add(new LocalGovt { StateId = 1, Name = "Isiala Ngwa South" });
            localGovts.Add(new LocalGovt { StateId = 1, Name = "Isuikwuato" });
            localGovts.Add(new LocalGovt { StateId = 1, Name = "Obi Ngwa" });
            localGovts.Add(new LocalGovt { StateId = 1, Name = "Ohafia" });
            localGovts.Add(new LocalGovt { StateId = 1, Name = "Osisioma" });
            localGovts.Add(new LocalGovt { StateId = 1, Name = "Ugwunagbo" });
            localGovts.Add(new LocalGovt { StateId = 1, Name = "Ukwa East" });
            localGovts.Add(new LocalGovt { StateId = 1, Name = "Ukwa West" });
            localGovts.Add(new LocalGovt { StateId = 1, Name = "Umuahia North" });
            localGovts.Add(new LocalGovt { StateId = 1, Name = "Umuahia South" });
            localGovts.Add(new LocalGovt { StateId = 1, Name = "Umu Nneochi" });
            localGovts.Add(new LocalGovt { StateId = 2, Name = "Demsa" });
            localGovts.Add(new LocalGovt { StateId = 2, Name = "Fufure" });
            localGovts.Add(new LocalGovt { StateId = 2, Name = "Ganye" });
            localGovts.Add(new LocalGovt { StateId = 2, Name = "Gayuk" });
            localGovts.Add(new LocalGovt { StateId = 2, Name = "Gombi" });
            localGovts.Add(new LocalGovt { StateId = 2, Name = "Grie" });
            localGovts.Add(new LocalGovt { StateId = 2, Name = "Hong" });
            localGovts.Add(new LocalGovt { StateId = 2, Name = "Jada" });
            localGovts.Add(new LocalGovt { StateId = 2, Name = "Larmurde" });
            localGovts.Add(new LocalGovt { StateId = 2, Name = "Madagali" });
            localGovts.Add(new LocalGovt { StateId = 2, Name = "Maiha" });
            localGovts.Add(new LocalGovt { StateId = 2, Name = "Mayo Belwa" });
            localGovts.Add(new LocalGovt { StateId = 2, Name = "Michika" });
            localGovts.Add(new LocalGovt { StateId = 2, Name = "Mubi North" });
            localGovts.Add(new LocalGovt { StateId = 2, Name = "Mubi South" });
            localGovts.Add(new LocalGovt { StateId = 2, Name = "Numan" });
            localGovts.Add(new LocalGovt { StateId = 2, Name = "Shelleng" });
            localGovts.Add(new LocalGovt { StateId = 2, Name = "Song" });
            localGovts.Add(new LocalGovt { StateId = 2, Name = "Toungo" });
            localGovts.Add(new LocalGovt { StateId = 2, Name = "Yola North" });
            localGovts.Add(new LocalGovt { StateId = 2, Name = "Yola South" });
            localGovts.Add(new LocalGovt { StateId = 3, Name = "Abak" });
            localGovts.Add(new LocalGovt { StateId = 3, Name = "Eastern Obolo" });
            localGovts.Add(new LocalGovt { StateId = 3, Name = "Eket" });
            localGovts.Add(new LocalGovt { StateId = 3, Name = "Esit Eket" });
            localGovts.Add(new LocalGovt { StateId = 3, Name = "Essien Udim" });
            localGovts.Add(new LocalGovt { StateId = 3, Name = "Etim Ekpo" });
            localGovts.Add(new LocalGovt { StateId = 3, Name = "Etinan" });
            localGovts.Add(new LocalGovt { StateId = 3, Name = "Ibeno" });
            localGovts.Add(new LocalGovt { StateId = 3, Name = "Ibesikpo Asutan" });
            localGovts.Add(new LocalGovt { StateId = 3, Name = "Ibiono-Ibom" });
            localGovts.Add(new LocalGovt { StateId = 3, Name = "Ika" });
            localGovts.Add(new LocalGovt { StateId = 3, Name = "Ikono" });
            localGovts.Add(new LocalGovt { StateId = 3, Name = "Ikot Abasi" });
            localGovts.Add(new LocalGovt { StateId = 3, Name = "Ikot Ekpene" });
            localGovts.Add(new LocalGovt { StateId = 3, Name = "Ini" });
            localGovts.Add(new LocalGovt { StateId = 3, Name = "Itu" });
            localGovts.Add(new LocalGovt { StateId = 3, Name = "Mbo" });
            localGovts.Add(new LocalGovt { StateId = 3, Name = "Mkpat-Enin" });
            localGovts.Add(new LocalGovt { StateId = 3, Name = "Nsit-Atai" });
            localGovts.Add(new LocalGovt { StateId = 3, Name = "Nsit-Ibom" });
            localGovts.Add(new LocalGovt { StateId = 3, Name = "Nsit-Ubium" });
            localGovts.Add(new LocalGovt { StateId = 3, Name = "Obot Akara" });
            localGovts.Add(new LocalGovt { StateId = 3, Name = "Okobo" });
            localGovts.Add(new LocalGovt { StateId = 3, Name = "Onna" });
            localGovts.Add(new LocalGovt { StateId = 3, Name = "Oron" });
            localGovts.Add(new LocalGovt { StateId = 3, Name = "Oruk Anam" });
            localGovts.Add(new LocalGovt { StateId = 3, Name = "Udung-Uko" });
            localGovts.Add(new LocalGovt { StateId = 3, Name = "Ukanafun" });
            localGovts.Add(new LocalGovt { StateId = 3, Name = "Uruan" });
            localGovts.Add(new LocalGovt { StateId = 3, Name = "Urue-Offong/Oruko" });
            localGovts.Add(new LocalGovt { StateId = 3, Name = "Uyo" });
            localGovts.Add(new LocalGovt { StateId = 4, Name = "Aguata" });
            localGovts.Add(new LocalGovt { StateId = 4, Name = "Anambra East" });
            localGovts.Add(new LocalGovt { StateId = 4, Name = "Anambra West" });
            localGovts.Add(new LocalGovt { StateId = 4, Name = "Anaocha" });
            localGovts.Add(new LocalGovt { StateId = 4, Name = "Awka North" });
            localGovts.Add(new LocalGovt { StateId = 4, Name = "Awka South" });
            localGovts.Add(new LocalGovt { StateId = 4, Name = "Ayamelum" });
            localGovts.Add(new LocalGovt { StateId = 4, Name = "Dunukofia" });
            localGovts.Add(new LocalGovt { StateId = 4, Name = "Ekwusigo" });
            localGovts.Add(new LocalGovt { StateId = 4, Name = "Idemili North" });
            localGovts.Add(new LocalGovt { StateId = 4, Name = "Idemili South" });
            localGovts.Add(new LocalGovt { StateId = 4, Name = "Ihiala" });
            localGovts.Add(new LocalGovt { StateId = 4, Name = "Njikoka" });
            localGovts.Add(new LocalGovt { StateId = 4, Name = "Nnewi North" });
            localGovts.Add(new LocalGovt { StateId = 4, Name = "Nnewi South" });
            localGovts.Add(new LocalGovt { StateId = 4, Name = "Ogbaru" });
            localGovts.Add(new LocalGovt { StateId = 4, Name = "Onitsha North" });
            localGovts.Add(new LocalGovt { StateId = 4, Name = "Onitsha South" });
            localGovts.Add(new LocalGovt { StateId = 4, Name = "Orumba North" });
            localGovts.Add(new LocalGovt { StateId = 4, Name = "Orumba South" });
            localGovts.Add(new LocalGovt { StateId = 4, Name = "Oyi" });
            localGovts.Add(new LocalGovt { StateId = 5, Name = "Alkaleri" });
            localGovts.Add(new LocalGovt { StateId = 5, Name = "Bauchi" });
            localGovts.Add(new LocalGovt { StateId = 5, Name = "Bogoro" });
            localGovts.Add(new LocalGovt { StateId = 5, Name = "Damban" });
            localGovts.Add(new LocalGovt { StateId = 5, Name = "Darazo" });
            localGovts.Add(new LocalGovt { StateId = 5, Name = "Dass" });
            localGovts.Add(new LocalGovt { StateId = 5, Name = "Gamawa" });
            localGovts.Add(new LocalGovt { StateId = 5, Name = "Ganjuwa" });
            localGovts.Add(new LocalGovt { StateId = 5, Name = "Giade" });
            localGovts.Add(new LocalGovt { StateId = 5, Name = "Itas/Gadau" });
            localGovts.Add(new LocalGovt { StateId = 5, Name = "Jama''are" });
            localGovts.Add(new LocalGovt { StateId = 5, Name = "Katagum" });
            localGovts.Add(new LocalGovt { StateId = 5, Name = "Kirfi" });
            localGovts.Add(new LocalGovt { StateId = 5, Name = "Misau" });
            localGovts.Add(new LocalGovt { StateId = 5, Name = "Ningi" });
            localGovts.Add(new LocalGovt { StateId = 5, Name = "Shira" });
            localGovts.Add(new LocalGovt { StateId = 5, Name = "Tafawa Balewa" });
            localGovts.Add(new LocalGovt { StateId = 5, Name = "Toro" });
            localGovts.Add(new LocalGovt { StateId = 5, Name = "Warji" });
            localGovts.Add(new LocalGovt { StateId = 5, Name = "Zaki" });
            localGovts.Add(new LocalGovt { StateId = 6, Name = "Brass" });
            localGovts.Add(new LocalGovt { StateId = 6, Name = "Ekeremor" });
            localGovts.Add(new LocalGovt { StateId = 6, Name = "Kolokuma/Opokuma" });
            localGovts.Add(new LocalGovt { StateId = 6, Name = "Nembe" });
            localGovts.Add(new LocalGovt { StateId = 6, Name = "Ogbia" });
            localGovts.Add(new LocalGovt { StateId = 6, Name = "Sagbama" });
            localGovts.Add(new LocalGovt { StateId = 6, Name = "Southern Ijaw" });
            localGovts.Add(new LocalGovt { StateId = 6, Name = "Yenagoa" });
            localGovts.Add(new LocalGovt { StateId = 7, Name = "Agatu" });
            localGovts.Add(new LocalGovt { StateId = 7, Name = "Apa" });
            localGovts.Add(new LocalGovt { StateId = 7, Name = "Ado" });
            localGovts.Add(new LocalGovt { StateId = 7, Name = "Buruku" });
            localGovts.Add(new LocalGovt { StateId = 7, Name = "Gboko" });
            localGovts.Add(new LocalGovt { StateId = 7, Name = "Guma" });
            localGovts.Add(new LocalGovt { StateId = 7, Name = "Gwer East" });
            localGovts.Add(new LocalGovt { StateId = 7, Name = "Gwer West" });
            localGovts.Add(new LocalGovt { StateId = 7, Name = "Katsina-Ala" });
            localGovts.Add(new LocalGovt { StateId = 7, Name = "Konshisha" });
            localGovts.Add(new LocalGovt { StateId = 7, Name = "Kwande" });
            localGovts.Add(new LocalGovt { StateId = 7, Name = "Logo" });
            localGovts.Add(new LocalGovt { StateId = 7, Name = "Makurdi" });
            localGovts.Add(new LocalGovt { StateId = 7, Name = "Obi" });
            localGovts.Add(new LocalGovt { StateId = 7, Name = "Ogbadibo" });
            localGovts.Add(new LocalGovt { StateId = 7, Name = "Ohimini" });
            localGovts.Add(new LocalGovt { StateId = 7, Name = "Oju" });
            localGovts.Add(new LocalGovt { StateId = 7, Name = "Okpokwu" });
            localGovts.Add(new LocalGovt { StateId = 7, Name = "Oturkpo" });
            localGovts.Add(new LocalGovt { StateId = 7, Name = "Tarka" });
            localGovts.Add(new LocalGovt { StateId = 7, Name = "Ukum" });
            localGovts.Add(new LocalGovt { StateId = 7, Name = "Ushongo" });
            localGovts.Add(new LocalGovt { StateId = 7, Name = "Vandeikya" });
            localGovts.Add(new LocalGovt { StateId = 8, Name = "Abadam" });
            localGovts.Add(new LocalGovt { StateId = 8, Name = "Askira/Uba" });
            localGovts.Add(new LocalGovt { StateId = 8, Name = "Bama" });
            localGovts.Add(new LocalGovt { StateId = 8, Name = "Bayo" });
            localGovts.Add(new LocalGovt { StateId = 8, Name = "Biu" });
            localGovts.Add(new LocalGovt { StateId = 8, Name = "Chibok" });
            localGovts.Add(new LocalGovt { StateId = 8, Name = "Damboa" });
            localGovts.Add(new LocalGovt { StateId = 8, Name = "Dikwa" });
            localGovts.Add(new LocalGovt { StateId = 8, Name = "Gubio" });
            localGovts.Add(new LocalGovt { StateId = 8, Name = "Guzamala" });
            localGovts.Add(new LocalGovt { StateId = 8, Name = "Gwoza" });
            localGovts.Add(new LocalGovt { StateId = 8, Name = "Hawul" });
            localGovts.Add(new LocalGovt { StateId = 8, Name = "Jere" });
            localGovts.Add(new LocalGovt { StateId = 8, Name = "Kaga" });
            localGovts.Add(new LocalGovt { StateId = 8, Name = "Kala/Balge" });
            localGovts.Add(new LocalGovt { StateId = 8, Name = "Konduga" });
            localGovts.Add(new LocalGovt { StateId = 8, Name = "Kukawa" });
            localGovts.Add(new LocalGovt { StateId = 8, Name = "Kwaya Kusar" });
            localGovts.Add(new LocalGovt { StateId = 8, Name = "Mafa" });
            localGovts.Add(new LocalGovt { StateId = 8, Name = "Magumeri" });
            localGovts.Add(new LocalGovt { StateId = 8, Name = "Maiduguri" });
            localGovts.Add(new LocalGovt { StateId = 8, Name = "Marte" });
            localGovts.Add(new LocalGovt { StateId = 8, Name = "Mobbar" });
            localGovts.Add(new LocalGovt { StateId = 8, Name = "Monguno" });
            localGovts.Add(new LocalGovt { StateId = 8, Name = "Ngala" });
            localGovts.Add(new LocalGovt { StateId = 8, Name = "Nganzai" });
            localGovts.Add(new LocalGovt { StateId = 8, Name = "Shani" });
            localGovts.Add(new LocalGovt { StateId = 9, Name = "Abi" });
            localGovts.Add(new LocalGovt { StateId = 9, Name = "Akamkpa" });
            localGovts.Add(new LocalGovt { StateId = 9, Name = "Akpabuyo" });
            localGovts.Add(new LocalGovt { StateId = 9, Name = "Bakassi" });
            localGovts.Add(new LocalGovt { StateId = 9, Name = "Bekwarra" });
            localGovts.Add(new LocalGovt { StateId = 9, Name = "Biase" });
            localGovts.Add(new LocalGovt { StateId = 9, Name = "Boki" });
            localGovts.Add(new LocalGovt { StateId = 9, Name = "Calabar Municipal" });
            localGovts.Add(new LocalGovt { StateId = 9, Name = "Calabar South" });
            localGovts.Add(new LocalGovt { StateId = 9, Name = "Etung" });
            localGovts.Add(new LocalGovt { StateId = 9, Name = "Ikom" });
            localGovts.Add(new LocalGovt { StateId = 9, Name = "Obanliku" });
            localGovts.Add(new LocalGovt { StateId = 9, Name = "Obubra" });
            localGovts.Add(new LocalGovt { StateId = 9, Name = "Obudu" });
            localGovts.Add(new LocalGovt { StateId = 9, Name = "Odukpani" });
            localGovts.Add(new LocalGovt { StateId = 9, Name = "Ogoja" });
            localGovts.Add(new LocalGovt { StateId = 9, Name = "Yakuur" });
            localGovts.Add(new LocalGovt { StateId = 9, Name = "Yala" });
            localGovts.Add(new LocalGovt { StateId = 10, Name = "Aniocha North" });
            localGovts.Add(new LocalGovt { StateId = 10, Name = "Aniocha South" });
            localGovts.Add(new LocalGovt { StateId = 10, Name = "Bomadi" });
            localGovts.Add(new LocalGovt { StateId = 10, Name = "Burutu" });
            localGovts.Add(new LocalGovt { StateId = 10, Name = "Ethiope East" });
            localGovts.Add(new LocalGovt { StateId = 10, Name = "Ethiope West" });
            localGovts.Add(new LocalGovt { StateId = 10, Name = "Ika North East" });
            localGovts.Add(new LocalGovt { StateId = 10, Name = "Ika South" });
            localGovts.Add(new LocalGovt { StateId = 10, Name = "Isoko North" });
            localGovts.Add(new LocalGovt { StateId = 10, Name = "Isoko South" });
            localGovts.Add(new LocalGovt { StateId = 10, Name = "Ndokwa East" });
            localGovts.Add(new LocalGovt { StateId = 10, Name = "Ndokwa West" });
            localGovts.Add(new LocalGovt { StateId = 10, Name = "Okpe" });
            localGovts.Add(new LocalGovt { StateId = 10, Name = "Oshimili North" });
            localGovts.Add(new LocalGovt { StateId = 10, Name = "Oshimili South" });
            localGovts.Add(new LocalGovt { StateId = 10, Name = "Patani" });
            localGovts.Add(new LocalGovt { StateId = 10, Name = "Sapele, Delta" });
            localGovts.Add(new LocalGovt { StateId = 10, Name = "Udu" });
            localGovts.Add(new LocalGovt { StateId = 10, Name = "Ughelli North" });
            localGovts.Add(new LocalGovt { StateId = 10, Name = "Ughelli South" });
            localGovts.Add(new LocalGovt { StateId = 10, Name = "Ukwuani" });
            localGovts.Add(new LocalGovt { StateId = 10, Name = "Uvwie" });
            localGovts.Add(new LocalGovt { StateId = 10, Name = "Warri North" });
            localGovts.Add(new LocalGovt { StateId = 10, Name = "Warri South" });
            localGovts.Add(new LocalGovt { StateId = 10, Name = "Warri South West" });
            localGovts.Add(new LocalGovt { StateId = 11, Name = "Abakaliki" });
            localGovts.Add(new LocalGovt { StateId = 11, Name = "Afikpo North" });
            localGovts.Add(new LocalGovt { StateId = 11, Name = "Afikpo South" });
            localGovts.Add(new LocalGovt { StateId = 11, Name = "Ebonyi" });
            localGovts.Add(new LocalGovt { StateId = 11, Name = "Ezza North" });
            localGovts.Add(new LocalGovt { StateId = 11, Name = "Ezza South" });
            localGovts.Add(new LocalGovt { StateId = 11, Name = "Ikwo" });
            localGovts.Add(new LocalGovt { StateId = 11, Name = "Ishielu" });
            localGovts.Add(new LocalGovt { StateId = 11, Name = "Ivo" });
            localGovts.Add(new LocalGovt { StateId = 11, Name = "Izzi" });
            localGovts.Add(new LocalGovt { StateId = 11, Name = "Ohaozara" });
            localGovts.Add(new LocalGovt { StateId = 11, Name = "Ohaukwu" });
            localGovts.Add(new LocalGovt { StateId = 11, Name = "Onicha" });
            localGovts.Add(new LocalGovt { StateId = 12, Name = "Akoko-Edo" });
            localGovts.Add(new LocalGovt { StateId = 12, Name = "Egor" });
            localGovts.Add(new LocalGovt { StateId = 12, Name = "Esan Central" });
            localGovts.Add(new LocalGovt { StateId = 12, Name = "Esan North-East" });
            localGovts.Add(new LocalGovt { StateId = 12, Name = "Esan South-East" });
            localGovts.Add(new LocalGovt { StateId = 12, Name = "Esan West" });
            localGovts.Add(new LocalGovt { StateId = 12, Name = "Etsako Central" });
            localGovts.Add(new LocalGovt { StateId = 12, Name = "Etsako East" });
            localGovts.Add(new LocalGovt { StateId = 12, Name = "Etsako West" });
            localGovts.Add(new LocalGovt { StateId = 12, Name = "Igueben" });
            localGovts.Add(new LocalGovt { StateId = 12, Name = "Ikpoba Okha" });
            localGovts.Add(new LocalGovt { StateId = 12, Name = "Orhionmwon" });
            localGovts.Add(new LocalGovt { StateId = 12, Name = "Oredo" });
            localGovts.Add(new LocalGovt { StateId = 12, Name = "Ovia North-East" });
            localGovts.Add(new LocalGovt { StateId = 12, Name = "Ovia South-West" });
            localGovts.Add(new LocalGovt { StateId = 12, Name = "Owan East" });
            localGovts.Add(new LocalGovt { StateId = 12, Name = "Owan West" });
            localGovts.Add(new LocalGovt { StateId = 12, Name = "Uhunmwonde" });
            localGovts.Add(new LocalGovt { StateId = 13, Name = "Ado Ekiti" });
            localGovts.Add(new LocalGovt { StateId = 13, Name = "Efon" });
            localGovts.Add(new LocalGovt { StateId = 13, Name = "Ekiti East" });
            localGovts.Add(new LocalGovt { StateId = 13, Name = "Ekiti South-West" });
            localGovts.Add(new LocalGovt { StateId = 13, Name = "Ekiti West" });
            localGovts.Add(new LocalGovt { StateId = 13, Name = "Emure" });
            localGovts.Add(new LocalGovt { StateId = 13, Name = "Gbonyin" });
            localGovts.Add(new LocalGovt { StateId = 13, Name = "Ido Osi" });
            localGovts.Add(new LocalGovt { StateId = 13, Name = "Ijero" });
            localGovts.Add(new LocalGovt { StateId = 13, Name = "Ikere" });
            localGovts.Add(new LocalGovt { StateId = 13, Name = "Ikole" });
            localGovts.Add(new LocalGovt { StateId = 13, Name = "Ilejemeje" });
            localGovts.Add(new LocalGovt { StateId = 13, Name = "Irepodun/Ifelodun" });
            localGovts.Add(new LocalGovt { StateId = 13, Name = "Ise/Orun" });
            localGovts.Add(new LocalGovt { StateId = 13, Name = "Moba" });
            localGovts.Add(new LocalGovt { StateId = 13, Name = "Oye" });
            localGovts.Add(new LocalGovt { StateId = 14, Name = "Aninri" });
            localGovts.Add(new LocalGovt { StateId = 14, Name = "Awgu" });
            localGovts.Add(new LocalGovt { StateId = 14, Name = "Enugu East" });
            localGovts.Add(new LocalGovt { StateId = 14, Name = "Enugu North" });
            localGovts.Add(new LocalGovt { StateId = 14, Name = "Enugu South" });
            localGovts.Add(new LocalGovt { StateId = 14, Name = "Ezeagu" });
            localGovts.Add(new LocalGovt { StateId = 14, Name = "Igbo Etiti" });
            localGovts.Add(new LocalGovt { StateId = 14, Name = "Igbo Eze North" });
            localGovts.Add(new LocalGovt { StateId = 14, Name = "Igbo Eze South" });
            localGovts.Add(new LocalGovt { StateId = 14, Name = "Isi Uzo" });
            localGovts.Add(new LocalGovt { StateId = 14, Name = "Nkanu East" });
            localGovts.Add(new LocalGovt { StateId = 14, Name = "Nkanu West" });
            localGovts.Add(new LocalGovt { StateId = 14, Name = "Nsukka" });
            localGovts.Add(new LocalGovt { StateId = 14, Name = "Oji River" });
            localGovts.Add(new LocalGovt { StateId = 14, Name = "Udenu" });
            localGovts.Add(new LocalGovt { StateId = 14, Name = "Udi" });
            localGovts.Add(new LocalGovt { StateId = 14, Name = "Uzo Uwani" });
            localGovts.Add(new LocalGovt { StateId = 15, Name = "Abaji" });
            localGovts.Add(new LocalGovt { StateId = 15, Name = "Bwari" });
            localGovts.Add(new LocalGovt { StateId = 15, Name = "Gwagwalada" });
            localGovts.Add(new LocalGovt { StateId = 15, Name = "Kuje" });
            localGovts.Add(new LocalGovt { StateId = 15, Name = "Kwali" });
            localGovts.Add(new LocalGovt { StateId = 15, Name = "Municipal Area Council" });
            localGovts.Add(new LocalGovt { StateId = 16, Name = "Akko" });
            localGovts.Add(new LocalGovt { StateId = 16, Name = "Balanga" });
            localGovts.Add(new LocalGovt { StateId = 16, Name = "Billiri" });
            localGovts.Add(new LocalGovt { StateId = 16, Name = "Dukku" });
            localGovts.Add(new LocalGovt { StateId = 16, Name = "Funakaye" });
            localGovts.Add(new LocalGovt { StateId = 16, Name = "Gombe" });
            localGovts.Add(new LocalGovt { StateId = 16, Name = "Kaltungo" });
            localGovts.Add(new LocalGovt { StateId = 16, Name = "Kwami" });
            localGovts.Add(new LocalGovt { StateId = 16, Name = "Nafada" });
            localGovts.Add(new LocalGovt { StateId = 16, Name = "Shongom" });
            localGovts.Add(new LocalGovt { StateId = 16, Name = "Yamaltu/Deba" });
            localGovts.Add(new LocalGovt { StateId = 17, Name = "Aboh Mbaise" });
            localGovts.Add(new LocalGovt { StateId = 17, Name = "Ahiazu Mbaise" });
            localGovts.Add(new LocalGovt { StateId = 17, Name = "Ehime Mbano" });
            localGovts.Add(new LocalGovt { StateId = 17, Name = "Ezinihitte" });
            localGovts.Add(new LocalGovt { StateId = 17, Name = "Ideato North" });
            localGovts.Add(new LocalGovt { StateId = 17, Name = "Ideato South" });
            localGovts.Add(new LocalGovt { StateId = 17, Name = "Ihitte/Uboma" });
            localGovts.Add(new LocalGovt { StateId = 17, Name = "Ikeduru" });
            localGovts.Add(new LocalGovt { StateId = 17, Name = "Isiala Mbano" });
            localGovts.Add(new LocalGovt { StateId = 17, Name = "Isu" });
            localGovts.Add(new LocalGovt { StateId = 17, Name = "Mbaitoli" });
            localGovts.Add(new LocalGovt { StateId = 17, Name = "Ngor Okpala" });
            localGovts.Add(new LocalGovt { StateId = 17, Name = "Njaba" });
            localGovts.Add(new LocalGovt { StateId = 17, Name = "Nkwerre" });
            localGovts.Add(new LocalGovt { StateId = 17, Name = "Nwangele" });
            localGovts.Add(new LocalGovt { StateId = 17, Name = "Obowo" });
            localGovts.Add(new LocalGovt { StateId = 17, Name = "Oguta" });
            localGovts.Add(new LocalGovt { StateId = 17, Name = "Ohaji/Egbema" });
            localGovts.Add(new LocalGovt { StateId = 17, Name = "Okigwe" });
            localGovts.Add(new LocalGovt { StateId = 17, Name = "Orlu" });
            localGovts.Add(new LocalGovt { StateId = 17, Name = "Orsu" });
            localGovts.Add(new LocalGovt { StateId = 17, Name = "Oru East" });
            localGovts.Add(new LocalGovt { StateId = 17, Name = "Oru West" });
            localGovts.Add(new LocalGovt { StateId = 17, Name = "Owerri Municipal" });
            localGovts.Add(new LocalGovt { StateId = 17, Name = "Owerri North" });
            localGovts.Add(new LocalGovt { StateId = 17, Name = "Owerri West" });
            localGovts.Add(new LocalGovt { StateId = 17, Name = "Unuimo" });
            localGovts.Add(new LocalGovt { StateId = 18, Name = "Auyo" });
            localGovts.Add(new LocalGovt { StateId = 18, Name = "Babura" });
            localGovts.Add(new LocalGovt { StateId = 18, Name = "Biriniwa" });
            localGovts.Add(new LocalGovt { StateId = 18, Name = "Birnin Kudu" });
            localGovts.Add(new LocalGovt { StateId = 18, Name = "Buji" });
            localGovts.Add(new LocalGovt { StateId = 18, Name = "Dutse" });
            localGovts.Add(new LocalGovt { StateId = 18, Name = "Gagarawa" });
            localGovts.Add(new LocalGovt { StateId = 18, Name = "Garki" });
            localGovts.Add(new LocalGovt { StateId = 18, Name = "Gumel" });
            localGovts.Add(new LocalGovt { StateId = 18, Name = "Guri" });
            localGovts.Add(new LocalGovt { StateId = 18, Name = "Gwaram" });
            localGovts.Add(new LocalGovt { StateId = 18, Name = "Gwiwa" });
            localGovts.Add(new LocalGovt { StateId = 18, Name = "Hadejia" });
            localGovts.Add(new LocalGovt { StateId = 18, Name = "Jahun" });
            localGovts.Add(new LocalGovt { StateId = 18, Name = "Kafin Hausa" });
            localGovts.Add(new LocalGovt { StateId = 18, Name = "Kazaure" });
            localGovts.Add(new LocalGovt { StateId = 18, Name = "Kiri Kasama" });
            localGovts.Add(new LocalGovt { StateId = 18, Name = "Kiyawa" });
            localGovts.Add(new LocalGovt { StateId = 18, Name = "Kaugama" });
            localGovts.Add(new LocalGovt { StateId = 18, Name = "Maigatari" });
            localGovts.Add(new LocalGovt { StateId = 18, Name = "Malam Madori" });
            localGovts.Add(new LocalGovt { StateId = 18, Name = "Miga" });
            localGovts.Add(new LocalGovt { StateId = 18, Name = "Ringim" });
            localGovts.Add(new LocalGovt { StateId = 18, Name = "Roni" });
            localGovts.Add(new LocalGovt { StateId = 18, Name = "Sule Tankarkar" });
            localGovts.Add(new LocalGovt { StateId = 18, Name = "Taura" });
            localGovts.Add(new LocalGovt { StateId = 18, Name = "Yankwashi" });
            localGovts.Add(new LocalGovt { StateId = 19, Name = "Birnin Gwari" });
            localGovts.Add(new LocalGovt { StateId = 19, Name = "Chikun" });
            localGovts.Add(new LocalGovt { StateId = 19, Name = "Giwa" });
            localGovts.Add(new LocalGovt { StateId = 19, Name = "Igabi" });
            localGovts.Add(new LocalGovt { StateId = 19, Name = "Ikara" });
            localGovts.Add(new LocalGovt { StateId = 19, Name = "Jaba" });
            localGovts.Add(new LocalGovt { StateId = 19, Name = "Jema''a" });
            localGovts.Add(new LocalGovt { StateId = 19, Name = "Kachia" });
            localGovts.Add(new LocalGovt { StateId = 19, Name = "Kaduna North" });
            localGovts.Add(new LocalGovt { StateId = 19, Name = "Kaduna South" });
            localGovts.Add(new LocalGovt { StateId = 19, Name = "Kagarko" });
            localGovts.Add(new LocalGovt { StateId = 19, Name = "Kajuru" });
            localGovts.Add(new LocalGovt { StateId = 19, Name = "Kaura" });
            localGovts.Add(new LocalGovt { StateId = 19, Name = "Kauru" });
            localGovts.Add(new LocalGovt { StateId = 19, Name = "Kubau" });
            localGovts.Add(new LocalGovt { StateId = 19, Name = "Kudan" });
            localGovts.Add(new LocalGovt { StateId = 19, Name = "Lere" });
            localGovts.Add(new LocalGovt { StateId = 19, Name = "Makarfi" });
            localGovts.Add(new LocalGovt { StateId = 19, Name = "Sabon Gari" });
            localGovts.Add(new LocalGovt { StateId = 19, Name = "Sanga" });
            localGovts.Add(new LocalGovt { StateId = 19, Name = "Soba" });
            localGovts.Add(new LocalGovt { StateId = 19, Name = "Zangon Kataf" });
            localGovts.Add(new LocalGovt { StateId = 19, Name = "Zaria" });
            localGovts.Add(new LocalGovt { StateId = 20, Name = "Ajingi" });
            localGovts.Add(new LocalGovt { StateId = 20, Name = "Albasu" });
            localGovts.Add(new LocalGovt { StateId = 20, Name = "Bagwai" });
            localGovts.Add(new LocalGovt { StateId = 20, Name = "Bebeji" });
            localGovts.Add(new LocalGovt { StateId = 20, Name = "Bichi" });
            localGovts.Add(new LocalGovt { StateId = 20, Name = "Bunkure" });
            localGovts.Add(new LocalGovt { StateId = 20, Name = "Dala" });
            localGovts.Add(new LocalGovt { StateId = 20, Name = "Dambatta" });
            localGovts.Add(new LocalGovt { StateId = 20, Name = "Dawakin Kudu" });
            localGovts.Add(new LocalGovt { StateId = 20, Name = "Dawakin Tofa" });
            localGovts.Add(new LocalGovt { StateId = 20, Name = "Doguwa" });
            localGovts.Add(new LocalGovt { StateId = 20, Name = "Fagge" });
            localGovts.Add(new LocalGovt { StateId = 20, Name = "Gabasawa" });
            localGovts.Add(new LocalGovt { StateId = 20, Name = "Garko" });
            localGovts.Add(new LocalGovt { StateId = 20, Name = "Garun Mallam" });
            localGovts.Add(new LocalGovt { StateId = 20, Name = "Gaya" });
            localGovts.Add(new LocalGovt { StateId = 20, Name = "Gezawa" });
            localGovts.Add(new LocalGovt { StateId = 20, Name = "Gwale" });
            localGovts.Add(new LocalGovt { StateId = 20, Name = "Gwarzo" });
            localGovts.Add(new LocalGovt { StateId = 20, Name = "Kabo" });
            localGovts.Add(new LocalGovt { StateId = 20, Name = "Kano Municipal" });
            localGovts.Add(new LocalGovt { StateId = 20, Name = "Karaye" });
            localGovts.Add(new LocalGovt { StateId = 20, Name = "Kibiya" });
            localGovts.Add(new LocalGovt { StateId = 20, Name = "Kiru" });
            localGovts.Add(new LocalGovt { StateId = 20, Name = "Kumbotso" });
            localGovts.Add(new LocalGovt { StateId = 20, Name = "Kunchi" });
            localGovts.Add(new LocalGovt { StateId = 20, Name = "Kura" });
            localGovts.Add(new LocalGovt { StateId = 20, Name = "Madobi" });
            localGovts.Add(new LocalGovt { StateId = 20, Name = "Makoda" });
            localGovts.Add(new LocalGovt { StateId = 20, Name = "Minjibir" });
            localGovts.Add(new LocalGovt { StateId = 20, Name = "Nasarawa" });
            localGovts.Add(new LocalGovt { StateId = 20, Name = "Rano" });
            localGovts.Add(new LocalGovt { StateId = 20, Name = "Rimin Gado" });
            localGovts.Add(new LocalGovt { StateId = 20, Name = "Rogo" });
            localGovts.Add(new LocalGovt { StateId = 20, Name = "Shanono" });
            localGovts.Add(new LocalGovt { StateId = 20, Name = "Sumaila" });
            localGovts.Add(new LocalGovt { StateId = 20, Name = "Takai" });
            localGovts.Add(new LocalGovt { StateId = 20, Name = "Tarauni" });
            localGovts.Add(new LocalGovt { StateId = 20, Name = "Tofa" });
            localGovts.Add(new LocalGovt { StateId = 20, Name = "Tsanyawa" });
            localGovts.Add(new LocalGovt { StateId = 20, Name = "Tudun Wada" });
            localGovts.Add(new LocalGovt { StateId = 20, Name = "Ungogo" });
            localGovts.Add(new LocalGovt { StateId = 20, Name = "Warawa" });
            localGovts.Add(new LocalGovt { StateId = 20, Name = "Wudil" });
            localGovts.Add(new LocalGovt { StateId = 21, Name = "Bakori" });
            localGovts.Add(new LocalGovt { StateId = 21, Name = "Batagarawa" });
            localGovts.Add(new LocalGovt { StateId = 21, Name = "Batsari" });
            localGovts.Add(new LocalGovt { StateId = 21, Name = "Baure" });
            localGovts.Add(new LocalGovt { StateId = 21, Name = "Bindawa" });
            localGovts.Add(new LocalGovt { StateId = 21, Name = "Charanchi" });
            localGovts.Add(new LocalGovt { StateId = 21, Name = "Dandume" });
            localGovts.Add(new LocalGovt { StateId = 21, Name = "Danja" });
            localGovts.Add(new LocalGovt { StateId = 21, Name = "Dan Musa" });
            localGovts.Add(new LocalGovt { StateId = 21, Name = "Daura" });
            localGovts.Add(new LocalGovt { StateId = 21, Name = "Dutsi" });
            localGovts.Add(new LocalGovt { StateId = 21, Name = "Dutsin Ma" });
            localGovts.Add(new LocalGovt { StateId = 21, Name = "Faskari" });
            localGovts.Add(new LocalGovt { StateId = 21, Name = "Funtua" });
            localGovts.Add(new LocalGovt { StateId = 21, Name = "Ingawa" });
            localGovts.Add(new LocalGovt { StateId = 21, Name = "Jibia" });
            localGovts.Add(new LocalGovt { StateId = 21, Name = "Kafur" });
            localGovts.Add(new LocalGovt { StateId = 21, Name = "Kaita" });
            localGovts.Add(new LocalGovt { StateId = 21, Name = "Kankara" });
            localGovts.Add(new LocalGovt { StateId = 21, Name = "Kankia" });
            localGovts.Add(new LocalGovt { StateId = 21, Name = "Katsina" });
            localGovts.Add(new LocalGovt { StateId = 21, Name = "Kurfi" });
            localGovts.Add(new LocalGovt { StateId = 21, Name = "Kusada" });
            localGovts.Add(new LocalGovt { StateId = 21, Name = "Mai''Adua" });
            localGovts.Add(new LocalGovt { StateId = 21, Name = "Malumfashi" });
            localGovts.Add(new LocalGovt { StateId = 21, Name = "Mani" });
            localGovts.Add(new LocalGovt { StateId = 21, Name = "Mashi" });
            localGovts.Add(new LocalGovt { StateId = 21, Name = "Matazu" });
            localGovts.Add(new LocalGovt { StateId = 21, Name = "Musawa" });
            localGovts.Add(new LocalGovt { StateId = 21, Name = "Rimi" });
            localGovts.Add(new LocalGovt { StateId = 21, Name = "Sabuwa" });
            localGovts.Add(new LocalGovt { StateId = 21, Name = "Safana" });
            localGovts.Add(new LocalGovt { StateId = 21, Name = "Sandamu" });
            localGovts.Add(new LocalGovt { StateId = 21, Name = "Zango" });
            localGovts.Add(new LocalGovt { StateId = 22, Name = "Aleiro" });
            localGovts.Add(new LocalGovt { StateId = 22, Name = "Arewa Dandi" });
            localGovts.Add(new LocalGovt { StateId = 22, Name = "Argungu" });
            localGovts.Add(new LocalGovt { StateId = 22, Name = "Augie" });
            localGovts.Add(new LocalGovt { StateId = 22, Name = "Bagudo" });
            localGovts.Add(new LocalGovt { StateId = 22, Name = "Birnin Kebbi" });
            localGovts.Add(new LocalGovt { StateId = 22, Name = "Bunza" });
            localGovts.Add(new LocalGovt { StateId = 22, Name = "Dandi" });
            localGovts.Add(new LocalGovt { StateId = 22, Name = "Fakai" });
            localGovts.Add(new LocalGovt { StateId = 22, Name = "Gwandu" });
            localGovts.Add(new LocalGovt { StateId = 22, Name = "Jega" });
            localGovts.Add(new LocalGovt { StateId = 22, Name = "Kalgo" });
            localGovts.Add(new LocalGovt { StateId = 22, Name = "Koko/Besse" });
            localGovts.Add(new LocalGovt { StateId = 22, Name = "Maiyama" });
            localGovts.Add(new LocalGovt { StateId = 22, Name = "Ngaski" });
            localGovts.Add(new LocalGovt { StateId = 22, Name = "Sakaba" });
            localGovts.Add(new LocalGovt { StateId = 22, Name = "Shanga" });
            localGovts.Add(new LocalGovt { StateId = 22, Name = "Suru" });
            localGovts.Add(new LocalGovt { StateId = 22, Name = "Wasagu/Danko" });
            localGovts.Add(new LocalGovt { StateId = 22, Name = "Yauri" });
            localGovts.Add(new LocalGovt { StateId = 22, Name = "Zuru" });
            localGovts.Add(new LocalGovt { StateId = 23, Name = "Adavi" });
            localGovts.Add(new LocalGovt { StateId = 23, Name = "Ajaokuta" });
            localGovts.Add(new LocalGovt { StateId = 23, Name = "Ankpa" });
            localGovts.Add(new LocalGovt { StateId = 23, Name = "Bassa" });
            localGovts.Add(new LocalGovt { StateId = 23, Name = "Dekina" });
            localGovts.Add(new LocalGovt { StateId = 23, Name = "Ibaji" });
            localGovts.Add(new LocalGovt { StateId = 23, Name = "Idah" });
            localGovts.Add(new LocalGovt { StateId = 23, Name = "Igalamela Odolu" });
            localGovts.Add(new LocalGovt { StateId = 23, Name = "Ijumu" });
            localGovts.Add(new LocalGovt { StateId = 23, Name = "Kabba/Bunu" });
            localGovts.Add(new LocalGovt { StateId = 23, Name = "Kogi" });
            localGovts.Add(new LocalGovt { StateId = 23, Name = "Lokoja" });
            localGovts.Add(new LocalGovt { StateId = 23, Name = "Mopa Muro" });
            localGovts.Add(new LocalGovt { StateId = 23, Name = "Ofu" });
            localGovts.Add(new LocalGovt { StateId = 23, Name = "Ogori/Magongo" });
            localGovts.Add(new LocalGovt { StateId = 23, Name = "Okehi" });
            localGovts.Add(new LocalGovt { StateId = 23, Name = "Okene" });
            localGovts.Add(new LocalGovt { StateId = 23, Name = "Olamaboro" });
            localGovts.Add(new LocalGovt { StateId = 23, Name = "Omala" });
            localGovts.Add(new LocalGovt { StateId = 23, Name = "Yagba East" });
            localGovts.Add(new LocalGovt { StateId = 23, Name = "Yagba West" });
            localGovts.Add(new LocalGovt { StateId = 24, Name = "Asa" });
            localGovts.Add(new LocalGovt { StateId = 24, Name = "Baruten" });
            localGovts.Add(new LocalGovt { StateId = 24, Name = "Edu" });
            localGovts.Add(new LocalGovt { StateId = 24, Name = "Ekiti, Kwara State" });
            localGovts.Add(new LocalGovt { StateId = 24, Name = "Ifelodun" });
            localGovts.Add(new LocalGovt { StateId = 24, Name = "Ilorin East" });
            localGovts.Add(new LocalGovt { StateId = 24, Name = "Ilorin South" });
            localGovts.Add(new LocalGovt { StateId = 24, Name = "Ilorin West" });
            localGovts.Add(new LocalGovt { StateId = 24, Name = "Irepodun" });
            localGovts.Add(new LocalGovt { StateId = 24, Name = "Isin" });
            localGovts.Add(new LocalGovt { StateId = 24, Name = "Kaiama" });
            localGovts.Add(new LocalGovt { StateId = 24, Name = "Moro" });
            localGovts.Add(new LocalGovt { StateId = 24, Name = "Offa" });
            localGovts.Add(new LocalGovt { StateId = 24, Name = "Oke Ero" });
            localGovts.Add(new LocalGovt { StateId = 24, Name = "Oyun" });
            localGovts.Add(new LocalGovt { StateId = 24, Name = "Pategi" });
            localGovts.Add(new LocalGovt { StateId = 25, Name = "Agege" });
            localGovts.Add(new LocalGovt { StateId = 25, Name = "Ajeromi-Ifelodun" });
            localGovts.Add(new LocalGovt { StateId = 25, Name = "Alimosho" });
            localGovts.Add(new LocalGovt { StateId = 25, Name = "Amuwo-Odofin" });
            localGovts.Add(new LocalGovt { StateId = 25, Name = "Apapa" });
            localGovts.Add(new LocalGovt { StateId = 25, Name = "Badagry" });
            localGovts.Add(new LocalGovt { StateId = 25, Name = "Epe" });
            localGovts.Add(new LocalGovt { StateId = 25, Name = "Eti Osa" });
            localGovts.Add(new LocalGovt { StateId = 25, Name = "Ibeju-Lekki" });
            localGovts.Add(new LocalGovt { StateId = 25, Name = "Ifako-Ijaiye" });
            localGovts.Add(new LocalGovt { StateId = 25, Name = "Ikeja" });
            localGovts.Add(new LocalGovt { StateId = 25, Name = "Ikorodu" });
            localGovts.Add(new LocalGovt { StateId = 25, Name = "Kosofe" });
            localGovts.Add(new LocalGovt { StateId = 25, Name = "Lagos Island" });
            localGovts.Add(new LocalGovt { StateId = 25, Name = "Lagos Mainland" });
            localGovts.Add(new LocalGovt { StateId = 25, Name = "Mushin" });
            localGovts.Add(new LocalGovt { StateId = 25, Name = "Ojo" });
            localGovts.Add(new LocalGovt { StateId = 25, Name = "Oshodi-Isolo" });
            localGovts.Add(new LocalGovt { StateId = 25, Name = "Shomolu" });
            localGovts.Add(new LocalGovt { StateId = 25, Name = "Surulere, Lagos State" });
            localGovts.Add(new LocalGovt { StateId = 26, Name = "Akwanga" });
            localGovts.Add(new LocalGovt { StateId = 26, Name = "Awe" });
            localGovts.Add(new LocalGovt { StateId = 26, Name = "Doma" });
            localGovts.Add(new LocalGovt { StateId = 26, Name = "Karu" });
            localGovts.Add(new LocalGovt { StateId = 26, Name = "Keana" });
            localGovts.Add(new LocalGovt { StateId = 26, Name = "Keffi" });
            localGovts.Add(new LocalGovt { StateId = 26, Name = "Kokona" });
            localGovts.Add(new LocalGovt { StateId = 26, Name = "Lafia" });
            localGovts.Add(new LocalGovt { StateId = 26, Name = "Nasarawa" });
            localGovts.Add(new LocalGovt { StateId = 26, Name = "Nasarawa Egon" });
            localGovts.Add(new LocalGovt { StateId = 26, Name = "Obi" });
            localGovts.Add(new LocalGovt { StateId = 26, Name = "Toto" });
            localGovts.Add(new LocalGovt { StateId = 26, Name = "Wamba" });
            localGovts.Add(new LocalGovt { StateId = 27, Name = "Agaie" });
            localGovts.Add(new LocalGovt { StateId = 27, Name = "Agwara" });
            localGovts.Add(new LocalGovt { StateId = 27, Name = "Bida" });
            localGovts.Add(new LocalGovt { StateId = 27, Name = "Borgu" });
            localGovts.Add(new LocalGovt { StateId = 27, Name = "Bosso" });
            localGovts.Add(new LocalGovt { StateId = 27, Name = "Chanchaga" });
            localGovts.Add(new LocalGovt { StateId = 27, Name = "Edati" });
            localGovts.Add(new LocalGovt { StateId = 27, Name = "Gbako" });
            localGovts.Add(new LocalGovt { StateId = 27, Name = "Gurara" });
            localGovts.Add(new LocalGovt { StateId = 27, Name = "Katcha" });
            localGovts.Add(new LocalGovt { StateId = 27, Name = "Kontagora" });
            localGovts.Add(new LocalGovt { StateId = 27, Name = "Lapai" });
            localGovts.Add(new LocalGovt { StateId = 27, Name = "Lavun" });
            localGovts.Add(new LocalGovt { StateId = 27, Name = "Magama" });
            localGovts.Add(new LocalGovt { StateId = 27, Name = "Mariga" });
            localGovts.Add(new LocalGovt { StateId = 27, Name = "Mashegu" });
            localGovts.Add(new LocalGovt { StateId = 27, Name = "Mokwa" });
            localGovts.Add(new LocalGovt { StateId = 27, Name = "Moya" });
            localGovts.Add(new LocalGovt { StateId = 27, Name = "Paikoro" });
            localGovts.Add(new LocalGovt { StateId = 27, Name = "Rafi" });
            localGovts.Add(new LocalGovt { StateId = 27, Name = "Rijau" });
            localGovts.Add(new LocalGovt { StateId = 27, Name = "Shiroro" });
            localGovts.Add(new LocalGovt { StateId = 27, Name = "Suleja" });
            localGovts.Add(new LocalGovt { StateId = 27, Name = "Tafa" });
            localGovts.Add(new LocalGovt { StateId = 27, Name = "Wushishi" });
            localGovts.Add(new LocalGovt { StateId = 28, Name = "Abeokuta North" });
            localGovts.Add(new LocalGovt { StateId = 28, Name = "Abeokuta South" });
            localGovts.Add(new LocalGovt { StateId = 28, Name = "Ado-Odo/Ota" });
            localGovts.Add(new LocalGovt { StateId = 28, Name = "Egbado North" });
            localGovts.Add(new LocalGovt { StateId = 28, Name = "Egbado South" });
            localGovts.Add(new LocalGovt { StateId = 28, Name = "Ewekoro" });
            localGovts.Add(new LocalGovt { StateId = 28, Name = "Ifo" });
            localGovts.Add(new LocalGovt { StateId = 28, Name = "Ijebu East" });
            localGovts.Add(new LocalGovt { StateId = 28, Name = "Ijebu North" });
            localGovts.Add(new LocalGovt { StateId = 28, Name = "Ijebu North East" });
            localGovts.Add(new LocalGovt { StateId = 28, Name = "Ijebu Ode" });
            localGovts.Add(new LocalGovt { StateId = 28, Name = "Ikenne" });
            localGovts.Add(new LocalGovt { StateId = 28, Name = "Imeko Afon" });
            localGovts.Add(new LocalGovt { StateId = 28, Name = "Ipokia" });
            localGovts.Add(new LocalGovt { StateId = 28, Name = "Obafemi Owode" });
            localGovts.Add(new LocalGovt { StateId = 28, Name = "Odeda" });
            localGovts.Add(new LocalGovt { StateId = 28, Name = "Odogbolu" });
            localGovts.Add(new LocalGovt { StateId = 28, Name = "Ogun Waterside" });
            localGovts.Add(new LocalGovt { StateId = 28, Name = "Remo North" });
            localGovts.Add(new LocalGovt { StateId = 28, Name = "Shagamu" });
            localGovts.Add(new LocalGovt { StateId = 29, Name = "Akoko North-East" });
            localGovts.Add(new LocalGovt { StateId = 29, Name = "Akoko North-West" });
            localGovts.Add(new LocalGovt { StateId = 29, Name = "Akoko South-West" });
            localGovts.Add(new LocalGovt { StateId = 29, Name = "Akoko South-East" });
            localGovts.Add(new LocalGovt { StateId = 29, Name = "Akure North" });
            localGovts.Add(new LocalGovt { StateId = 29, Name = "Akure South" });
            localGovts.Add(new LocalGovt { StateId = 29, Name = "Ese Odo" });
            localGovts.Add(new LocalGovt { StateId = 29, Name = "Idanre" });
            localGovts.Add(new LocalGovt { StateId = 29, Name = "Ifedore" });
            localGovts.Add(new LocalGovt { StateId = 29, Name = "Ilaje" });
            localGovts.Add(new LocalGovt { StateId = 29, Name = "Ile Oluji/Okeigbo" });
            localGovts.Add(new LocalGovt { StateId = 29, Name = "Irele" });
            localGovts.Add(new LocalGovt { StateId = 29, Name = "Odigbo" });
            localGovts.Add(new LocalGovt { StateId = 29, Name = "Okitipupa" });
            localGovts.Add(new LocalGovt { StateId = 29, Name = "Ondo East" });
            localGovts.Add(new LocalGovt { StateId = 29, Name = "Ondo West" });
            localGovts.Add(new LocalGovt { StateId = 29, Name = "Ose" });
            localGovts.Add(new LocalGovt { StateId = 29, Name = "Owo" });
            localGovts.Add(new LocalGovt { StateId = 30, Name = "Atakunmosa East" });
            localGovts.Add(new LocalGovt { StateId = 30, Name = "Atakunmosa West" });
            localGovts.Add(new LocalGovt { StateId = 30, Name = "Aiyedaade" });
            localGovts.Add(new LocalGovt { StateId = 30, Name = "Aiyedire" });
            localGovts.Add(new LocalGovt { StateId = 30, Name = "Boluwaduro" });
            localGovts.Add(new LocalGovt { StateId = 30, Name = "Boripe" });
            localGovts.Add(new LocalGovt { StateId = 30, Name = "Ede North" });
            localGovts.Add(new LocalGovt { StateId = 30, Name = "Ede South" });
            localGovts.Add(new LocalGovt { StateId = 30, Name = "Ife Central" });
            localGovts.Add(new LocalGovt { StateId = 30, Name = "Ife East" });
            localGovts.Add(new LocalGovt { StateId = 30, Name = "Ife North" });
            localGovts.Add(new LocalGovt { StateId = 30, Name = "Ife South" });
            localGovts.Add(new LocalGovt { StateId = 30, Name = "Egbedore" });
            localGovts.Add(new LocalGovt { StateId = 30, Name = "Ejigbo" });
            localGovts.Add(new LocalGovt { StateId = 30, Name = "Ifedayo" });
            localGovts.Add(new LocalGovt { StateId = 30, Name = "Ifelodun" });
            localGovts.Add(new LocalGovt { StateId = 30, Name = "Ila" });
            localGovts.Add(new LocalGovt { StateId = 30, Name = "Ilesa East" });
            localGovts.Add(new LocalGovt { StateId = 30, Name = "Ilesa West" });
            localGovts.Add(new LocalGovt { StateId = 30, Name = "Irepodun" });
            localGovts.Add(new LocalGovt { StateId = 30, Name = "Irewole" });
            localGovts.Add(new LocalGovt { StateId = 30, Name = "Isokan" });
            localGovts.Add(new LocalGovt { StateId = 30, Name = "Iwo" });
            localGovts.Add(new LocalGovt { StateId = 30, Name = "Obokun" });
            localGovts.Add(new LocalGovt { StateId = 30, Name = "Odo Otin" });
            localGovts.Add(new LocalGovt { StateId = 30, Name = "Ola Oluwa" });
            localGovts.Add(new LocalGovt { StateId = 30, Name = "Olorunda" });
            localGovts.Add(new LocalGovt { StateId = 30, Name = "Oriade" });
            localGovts.Add(new LocalGovt { StateId = 30, Name = "Orolu" });
            localGovts.Add(new LocalGovt { StateId = 30, Name = "Osogbo" });
            localGovts.Add(new LocalGovt { StateId = 31, Name = "Afijio" });
            localGovts.Add(new LocalGovt { StateId = 31, Name = "Akinyele" });
            localGovts.Add(new LocalGovt { StateId = 31, Name = "Atiba" });
            localGovts.Add(new LocalGovt { StateId = 31, Name = "Atisbo" });
            localGovts.Add(new LocalGovt { StateId = 31, Name = "Egbeda" });
            localGovts.Add(new LocalGovt { StateId = 31, Name = "Ibadan North" });
            localGovts.Add(new LocalGovt { StateId = 31, Name = "Ibadan North-East" });
            localGovts.Add(new LocalGovt { StateId = 31, Name = "Ibadan North-West" });
            localGovts.Add(new LocalGovt { StateId = 31, Name = "Ibadan South-East" });
            localGovts.Add(new LocalGovt { StateId = 31, Name = "Ibadan South-West" });
            localGovts.Add(new LocalGovt { StateId = 31, Name = "Ibarapa Central" });
            localGovts.Add(new LocalGovt { StateId = 31, Name = "Ibarapa East" });
            localGovts.Add(new LocalGovt { StateId = 31, Name = "Ibarapa North" });
            localGovts.Add(new LocalGovt { StateId = 31, Name = "Ido" });
            localGovts.Add(new LocalGovt { StateId = 31, Name = "Irepo" });
            localGovts.Add(new LocalGovt { StateId = 31, Name = "Iseyin" });
            localGovts.Add(new LocalGovt { StateId = 31, Name = "Itesiwaju" });
            localGovts.Add(new LocalGovt { StateId = 31, Name = "Iwajowa" });
            localGovts.Add(new LocalGovt { StateId = 31, Name = "Kajola" });
            localGovts.Add(new LocalGovt { StateId = 31, Name = "Lagelu" });
            localGovts.Add(new LocalGovt { StateId = 31, Name = "Ogbomosho North" });
            localGovts.Add(new LocalGovt { StateId = 31, Name = "Ogbomosho South" });
            localGovts.Add(new LocalGovt { StateId = 31, Name = "Ogo Oluwa" });
            localGovts.Add(new LocalGovt { StateId = 31, Name = "Olorunsogo" });
            localGovts.Add(new LocalGovt { StateId = 31, Name = "Oluyole" });
            localGovts.Add(new LocalGovt { StateId = 31, Name = "Ona Ara" });
            localGovts.Add(new LocalGovt { StateId = 31, Name = "Orelope" });
            localGovts.Add(new LocalGovt { StateId = 31, Name = "Ori Ire" });
            localGovts.Add(new LocalGovt { StateId = 31, Name = "Oyo" });
            localGovts.Add(new LocalGovt { StateId = 31, Name = "Oyo East" });
            localGovts.Add(new LocalGovt { StateId = 31, Name = "Saki East" });
            localGovts.Add(new LocalGovt { StateId = 31, Name = "Saki West" });
            localGovts.Add(new LocalGovt { StateId = 31, Name = "Surulere, Oyo State" });
            localGovts.Add(new LocalGovt { StateId = 32, Name = "Bokkos" });
            localGovts.Add(new LocalGovt { StateId = 32, Name = "Barkin Ladi" });
            localGovts.Add(new LocalGovt { StateId = 32, Name = "Bassa" });
            localGovts.Add(new LocalGovt { StateId = 32, Name = "Jos East" });
            localGovts.Add(new LocalGovt { StateId = 32, Name = "Jos North" });
            localGovts.Add(new LocalGovt { StateId = 32, Name = "Jos South" });
            localGovts.Add(new LocalGovt { StateId = 32, Name = "Kanam" });
            localGovts.Add(new LocalGovt { StateId = 32, Name = "Kanke" });
            localGovts.Add(new LocalGovt { StateId = 32, Name = "Langtang South" });
            localGovts.Add(new LocalGovt { StateId = 32, Name = "Langtang North" });
            localGovts.Add(new LocalGovt { StateId = 32, Name = "Mangu" });
            localGovts.Add(new LocalGovt { StateId = 32, Name = "Mikang" });
            localGovts.Add(new LocalGovt { StateId = 32, Name = "Pankshin" });
            localGovts.Add(new LocalGovt { StateId = 32, Name = "Qua''an Pan" });
            localGovts.Add(new LocalGovt { StateId = 32, Name = "Riyom" });
            localGovts.Add(new LocalGovt { StateId = 32, Name = "Shendam" });
            localGovts.Add(new LocalGovt { StateId = 32, Name = "Wase" });
            localGovts.Add(new LocalGovt { StateId = 33, Name = "Abua/Odual" });
            localGovts.Add(new LocalGovt { StateId = 33, Name = "Ahoada East" });
            localGovts.Add(new LocalGovt { StateId = 33, Name = "Ahoada West" });
            localGovts.Add(new LocalGovt { StateId = 33, Name = "Akuku-Toru" });
            localGovts.Add(new LocalGovt { StateId = 33, Name = "Andoni" });
            localGovts.Add(new LocalGovt { StateId = 33, Name = "Asari-Toru" });
            localGovts.Add(new LocalGovt { StateId = 33, Name = "Bonny" });
            localGovts.Add(new LocalGovt { StateId = 33, Name = "Degema" });
            localGovts.Add(new LocalGovt { StateId = 33, Name = "Eleme" });
            localGovts.Add(new LocalGovt { StateId = 33, Name = "Emuoha" });
            localGovts.Add(new LocalGovt { StateId = 33, Name = "Etche" });
            localGovts.Add(new LocalGovt { StateId = 33, Name = "Gokana" });
            localGovts.Add(new LocalGovt { StateId = 33, Name = "Ikwerre" });
            localGovts.Add(new LocalGovt { StateId = 33, Name = "Khana" });
            localGovts.Add(new LocalGovt { StateId = 33, Name = "Obio/Akpor" });
            localGovts.Add(new LocalGovt { StateId = 33, Name = "Ogba/Egbema/Ndoni" });
            localGovts.Add(new LocalGovt { StateId = 33, Name = "Ogu/Bolo" });
            localGovts.Add(new LocalGovt { StateId = 33, Name = "Okrika" });
            localGovts.Add(new LocalGovt { StateId = 33, Name = "Omuma" });
            localGovts.Add(new LocalGovt { StateId = 33, Name = "Opobo/Nkoro" });
            localGovts.Add(new LocalGovt { StateId = 33, Name = "Oyigbo" });
            localGovts.Add(new LocalGovt { StateId = 33, Name = "Port Harcourt" });
            localGovts.Add(new LocalGovt { StateId = 33, Name = "Tai" });
            localGovts.Add(new LocalGovt { StateId = 34, Name = "Binji" });
            localGovts.Add(new LocalGovt { StateId = 34, Name = "Bodinga" });
            localGovts.Add(new LocalGovt { StateId = 34, Name = "Dange Shuni" });
            localGovts.Add(new LocalGovt { StateId = 34, Name = "Gada" });
            localGovts.Add(new LocalGovt { StateId = 34, Name = "Goronyo" });
            localGovts.Add(new LocalGovt { StateId = 34, Name = "Gudu" });
            localGovts.Add(new LocalGovt { StateId = 34, Name = "Gwadabawa" });
            localGovts.Add(new LocalGovt { StateId = 34, Name = "Illela" });
            localGovts.Add(new LocalGovt { StateId = 34, Name = "Isa" });
            localGovts.Add(new LocalGovt { StateId = 34, Name = "Kebbe" });
            localGovts.Add(new LocalGovt { StateId = 34, Name = "Kware" });
            localGovts.Add(new LocalGovt { StateId = 34, Name = "Rabah" });
            localGovts.Add(new LocalGovt { StateId = 34, Name = "Sabon Birni" });
            localGovts.Add(new LocalGovt { StateId = 34, Name = "Shagari" });
            localGovts.Add(new LocalGovt { StateId = 34, Name = "Silame" });
            localGovts.Add(new LocalGovt { StateId = 34, Name = "Sokoto North" });
            localGovts.Add(new LocalGovt { StateId = 34, Name = "Sokoto South" });
            localGovts.Add(new LocalGovt { StateId = 34, Name = "Tambuwal" });
            localGovts.Add(new LocalGovt { StateId = 34, Name = "Tangaza" });
            localGovts.Add(new LocalGovt { StateId = 34, Name = "Tureta" });
            localGovts.Add(new LocalGovt { StateId = 34, Name = "Wamako" });
            localGovts.Add(new LocalGovt { StateId = 34, Name = "Wurno" });
            localGovts.Add(new LocalGovt { StateId = 34, Name = "Yabo" });
            localGovts.Add(new LocalGovt { StateId = 35, Name = "Ardo Kola" });
            localGovts.Add(new LocalGovt { StateId = 35, Name = "Bali" });
            localGovts.Add(new LocalGovt { StateId = 35, Name = "Donga" });
            localGovts.Add(new LocalGovt { StateId = 35, Name = "Gashaka" });
            localGovts.Add(new LocalGovt { StateId = 35, Name = "Gassol" });
            localGovts.Add(new LocalGovt { StateId = 35, Name = "Ibi" });
            localGovts.Add(new LocalGovt { StateId = 35, Name = "Jalingo" });
            localGovts.Add(new LocalGovt { StateId = 35, Name = "Karim Lamido" });
            localGovts.Add(new LocalGovt { StateId = 35, Name = "Kumi" });
            localGovts.Add(new LocalGovt { StateId = 35, Name = "Lau" });
            localGovts.Add(new LocalGovt { StateId = 35, Name = "Sardauna" });
            localGovts.Add(new LocalGovt { StateId = 35, Name = "Takum" });
            localGovts.Add(new LocalGovt { StateId = 35, Name = "Ussa" });
            localGovts.Add(new LocalGovt { StateId = 35, Name = "Wukari" });
            localGovts.Add(new LocalGovt { StateId = 35, Name = "Yorro" });
            localGovts.Add(new LocalGovt { StateId = 35, Name = "Zing" });
            localGovts.Add(new LocalGovt { StateId = 36, Name = "Bade" });
            localGovts.Add(new LocalGovt { StateId = 36, Name = "Bursari" });
            localGovts.Add(new LocalGovt { StateId = 36, Name = "Damaturu" });
            localGovts.Add(new LocalGovt { StateId = 36, Name = "Fika" });
            localGovts.Add(new LocalGovt { StateId = 36, Name = "Fune" });
            localGovts.Add(new LocalGovt { StateId = 36, Name = "Geidam" });
            localGovts.Add(new LocalGovt { StateId = 36, Name = "Gujba" });
            localGovts.Add(new LocalGovt { StateId = 36, Name = "Gulani" });
            localGovts.Add(new LocalGovt { StateId = 36, Name = "Jakusko" });
            localGovts.Add(new LocalGovt { StateId = 36, Name = "Karasuwa" });
            localGovts.Add(new LocalGovt { StateId = 36, Name = "Machina" });
            localGovts.Add(new LocalGovt { StateId = 36, Name = "Nangere" });
            localGovts.Add(new LocalGovt { StateId = 36, Name = "Nguru" });
            localGovts.Add(new LocalGovt { StateId = 36, Name = "Potiskum" });
            localGovts.Add(new LocalGovt { StateId = 36, Name = "Tarmuwa" });
            localGovts.Add(new LocalGovt { StateId = 36, Name = "Yunusari" });
            localGovts.Add(new LocalGovt { StateId = 36, Name = "Yusufari" });
            localGovts.Add(new LocalGovt { StateId = 37, Name = "Anka" });
            localGovts.Add(new LocalGovt { StateId = 37, Name = "Bakura" });
            localGovts.Add(new LocalGovt { StateId = 37, Name = "Birnin Magaji/Kiyaw" });
            localGovts.Add(new LocalGovt { StateId = 37, Name = "Bukkuyum" });
            localGovts.Add(new LocalGovt { StateId = 37, Name = "Bungudu" });
            localGovts.Add(new LocalGovt { StateId = 37, Name = "Gummi" });
            localGovts.Add(new LocalGovt { StateId = 37, Name = "Gusau" });
            localGovts.Add(new LocalGovt { StateId = 37, Name = "Kaura Namoda" });
            localGovts.Add(new LocalGovt { StateId = 37, Name = "Maradun" });
            localGovts.Add(new LocalGovt { StateId = 37, Name = "Maru" });
            localGovts.Add(new LocalGovt { StateId = 37, Name = "Shinkafi" });
            localGovts.Add(new LocalGovt { StateId = 37, Name = "Talata Mafara" });
            localGovts.Add(new LocalGovt { StateId = 37, Name = "Chafe" });
            localGovts.Add(new LocalGovt { StateId = 37, Name = "Zurmi" });
            int count = 1;
            localGovts.ForEach(x => x.Id = count++);

            return localGovts;
        }
    }
}
